# AppKit

target 'AppKit Sample (Obj-C, Pods)' do
  platform :osx, '11.5'
  pod 'Setapp', :path => '../'
end

target 'AppKit Sample (Swift, Pods)' do
  platform :osx, '11.5'
  pod 'Setapp', :path => '../'
end

# UIKit

target 'UIKit Sample (Obj-C, Pods)' do
  platform :ios, '15.6'
  pod 'Setapp', :path => '../'
end

target 'UIKit Sample (Swift, Pods)' do
  platform :ios, '15.6'
  pod 'Setapp', :path => '../'
end
