#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef SETAPP_SWIFT_H
#define SETAPP_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Setapp",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Setapp",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@interface NSHTTPURLResponse (SWIFT_EXTENSION(Setapp))
/// Backend request identifier.
@property (nonatomic, readonly, copy) NSString * _Nullable requestID;
@end

typedef SWIFT_ENUM(NSInteger, LicenseValidationStatus, closed) {
  LicenseValidationStatusSuccess = 1000,
  LicenseValidationStatusEmptyWorkingDataError = 1010,
  LicenseValidationStatusEmptyServerStatusDataError = 1011,
  LicenseValidationStatusEmptySignatureDataError = 1012,
  LicenseValidationStatusEmptyEncryptedDataError = 1013,
  LicenseValidationStatusDecryptedLicenseDataError = 1014,
  LicenseValidationStatusWorkingDataInvalid = 1020,
  LicenseValidationStatusPublicKeyInvalidError = 1021,
  LicenseValidationStatusSignatureInvalidError = 1022,
  LicenseValidationStatusDecryptionFailedError = 1023,
  LicenseValidationStatusLicenseExpiredError = 1024,
  LicenseValidationStatusUserSysTimeInvalidError = 1025,
  LicenseValidationStatusCrackedError = 1100,
  LicenseValidationStatusBackendReturnedErrorError = 1030,
  LicenseValidationStatusUnknownError = 1999,
};

@interface NSError (SWIFT_EXTENSION(Setapp))
- (nonnull instancetype)initWithCFError:(CFErrorRef _Nonnull)cfError;
@end

@class NSBundle;
/// A configuration object that holds necessary information for the operation of the Setapp
/// framework.
SWIFT_CLASS_NAMED("SetappConfiguration")
@interface STPConfiguration : NSObject
/// The default configuration for the current app.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) STPConfiguration * _Nonnull defaultConfiguration;)
+ (STPConfiguration * _Nonnull)defaultConfiguration SWIFT_WARN_UNUSED_RESULT;
/// An app group identifier used to store usage reports from app extension.
@property (nonatomic, readonly, copy) NSString * _Nullable appGroupIdentifier;
/// A bundle containing a public key file.
@property (nonatomic, readonly, strong) NSBundle * _Nonnull publicKeyBundle;
/// A public key filename.
@property (nonatomic, readonly, copy) NSString * _Nonnull publicKeyFilename;
/// Creates a new configuration with the given parameters.
/// \param publicKeyBundle A bundle containing a public key file. If <code>nil</code>, the main bundle is
/// used.
///
/// \param publicKeyFilename A name of a public key file. If <code>nil</code>, the <code>setappPublicKey.pem</code>
/// string is used.
///
/// \param appGroupIdentifier An app group identifier used to store usage reports from app extension.
///
- (nonnull instancetype)initWithPublicKeyBundle:(NSBundle * _Nullable)publicKeyBundle publicKeyFilename:(NSString * _Nullable)publicKeyFilename appGroupIdentifier:(NSString * _Nullable)appGroupIdentifier OBJC_DESIGNATED_INITIALIZER;
/// Returns a Boolean value that indicates whether the configuration and a given object are
/// equal.
/// \param object The object to be compared to the configuration. May be nil, in which
/// case this method returns false.
///
///
/// returns:
/// <code>true</code> if the configuration and <code>object</code> are equal, otherwise <code>false</code>.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// A textual representation of the configuration.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Setapp log levels.
typedef SWIFT_ENUM_NAMED(NSInteger, STPLogLevel, "SetappLogLevel", open) {
/// Error, warning, information, debug, and verbose logs.
  STPLogLevelVerbose = 0,
/// Error, warning, and information logs.
  STPLogLevelDebug = 1,
/// Error, warning, and information logs.
  STPLogLevelInfo = 2,
/// Error and warning logs.
  STPLogLevelWarning = 3,
/// Error logs only.
  STPLogLevelError = 4,
/// No logs.
  STPLogLevelOff = 5,
};

@protocol STPManagerDelegate;
@class STPSubscription;
@class NSURL;
@class UIOpenURLContext;
/// An object that provides an interface for the Setapp framework.
SWIFT_CLASS_NAMED("SetappManager")
@interface STPManager : NSObject
/// An object that handles Setapp subscription updates.
@property (nonatomic, strong) id <STPManagerDelegate> _Nullable delegate;
/// A current Setapp subscription.
@property (nonatomic, readonly, strong) STPSubscription * _Nullable subscription;
/// Returns <code>true</code> if a URL can be processed by the Setapp iOS Framework; otherwise <code>false</code>.
/// \param url A URL to validate.
///
- (BOOL)canOpenURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Returns <code>true</code> if at least one of the URL contexts could be opened by the Setapp iOS Framework,
/// otherwise <code>false</code>.
/// \param urlContexts A set of one or more <code>UIOpenURLContext</code> objects.
///
- (BOOL)canOpenURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)urlContexts SWIFT_WARN_UNUSED_RESULT;
/// A handler to call after handling background URL session events.
@property (nonatomic, copy) void (^ _Nullable backgroundSessionCompletionHandler)(void) SWIFT_DEPRECATED_MSG("This variable is not needed anymore.");
/// Checks if a provided URL session <code>identifier</code> was created by the Setapp framework or not.
/// Returns <code>true</code> if a provided identifier represents background Setapp URL session,
/// otherwise - <code>false</code>.
/// \param identifier The identifier of the URL session to check.
///
+ (BOOL)isSetappBackgroundConfigurationIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT;
/// Checks if a provided URL session <code>identifier</code> was created by the Setapp framework or not.
/// Returns <code>true</code> if a provided identifier represents background Setapp URL session,
/// otherwise - <code>false</code>.
/// \param identifier The identifier of the URL session to check.
///
- (BOOL)isSetappBackgroundSessionIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Instance method is deprecated use the class method instead: \"SetappManager.isSetappBackgroundSessionIdentifier\".");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface STPManager (SWIFT_EXTENSION(Setapp))
/// Requests an authorization code for communication with Setapp backend server.
/// The code is used to obtain the access & refresh tokens from the Vendor API.
/// This method requires an active Setapp subscription and an Internet connection,
/// otherwise the request fails with a corresponding error.
/// \param clientID A string ID generated for the app’s client in the Setapp developer account.
///
/// \param scope An array of case-sensitive strings that specify the scope of functionalities
/// to be authorized for the app’s client. See the full list of possible values in the
/// <a href="https://docs.setapp.com/reference#authorization-code-by-setapp-library-grant">Vendor API reference</a>.
///
/// \param completionHandler A completion handler to call once the auth code has been fetched.
/// The handler is executed on the main thread. Accepts one parameter:
/// <code>result</code>
/// A <code>Result</code> with a <code>String</code> as a success value if the code has
/// been fetched successfully. Otherwise, it’s a failure with an error
/// describing why the request failed.
///
- (void)requestAuthorizationCodeWithClientID:(NSString * _Nonnull)clientID scope:(NSArray<NSString *> * _Nonnull)scope completionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
@end

@interface STPManager (SWIFT_EXTENSION(Setapp))
/// Attempts to open a Setapp URL.
/// \param url A URL to open.
///
/// \param options A dictionary of URL handling options.
///
/// \param completionHandler A completion handler to call when the Setapp subscription state is
/// resolved.
/// The handler will be executed on the main thread. Accepts two parameters:
/// <code>setappSubscription</code>
/// <code>SetappSubscription</code> if Setapp subscription has been fetched successfully and is valid,
/// or <code>nil</code> if the subscription validation fails.
/// <code>error</code>
/// An error object that specifies why the Setapp subscription validation has failed, or
/// <code>nil</code> if the request was successful.
///
- (BOOL)openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options completionHandler:(void (^ _Nullable)(STPSubscription * _Nullable, NSError * _Nullable))completionHandler SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(maccatalyst,introduced=13.1,deprecated=26.0,message="Use UIScene lifecycle and equivalent properties on UISceneOpenURLOptions from a UIOpenURLContext in UIScene.ConnectionOptions.URLContexts instead.") SWIFT_AVAILABILITY(ios,introduced=9.0,deprecated=26.0,message="Use UIScene lifecycle and equivalent properties on UISceneOpenURLOptions from a UIOpenURLContext in UIScene.ConnectionOptions.URLContexts instead.");
/// Opens Setapp URLs.
/// \param urlContexts A set of one or more <code>UIOpenURLContext</code> objects.
///
/// \param completionHandler A completion handler to call when the Setapp subscription state is
/// resolved.
/// The handler will be executed on the main thread. Accepts two parameters:
/// <code>setappSubscription</code>
/// <code>SetappSubscription</code> if Setapp subscription has been fetched successfully and is valid,
/// or <code>nil</code> if the subscription validation fails.
/// <code>error</code>
/// An error object that specifies why the Setapp subscription validation has failed, or
/// <code>nil</code> if the request was successful.
///
- (void)openURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)urlContexts completionHandler:(void (^ _Nonnull)(STPSubscription * _Nullable, NSError * _Nullable))completionHandler;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, STPUsageEvent)
@interface STPManager (SWIFT_EXTENSION(Setapp))
/// Posted when a current Setapp subscription changes.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull didChangeSubscriptionNotification;)
+ (NSNotificationName _Nonnull)didChangeSubscriptionNotification SWIFT_WARN_UNUSED_RESULT;
/// A shared Setapp manager object for an application.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) STPManager * _Nonnull sharedInstance;)
+ (STPManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Current log level.
/// Default value: <code>SetappLogLevel.info</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum STPLogLevel logLevel;)
+ (enum STPLogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogLevel:(enum STPLogLevel)newValue;
/// Sets a log handle for Setapp log messages.
/// \param logHandle A closure to handle log messages. Can be <code>nil</code>. If <code>logHandle</code> is
/// not <code>nil</code>, no messages are printed in the device console.
///
+ (void)setLogHandle:(void (^ _Nullable)(NSString * _Nonnull, enum STPLogLevel))logHandle;
/// Starts the Setapp iOS Framework with a provided configuration.
/// We strongly recommend to call this method as soon as your app opens. You can do this in the
/// <code>application(_:, didFinishLaunchingWithOptions:)</code> method of your <code>UIApplicationDelegate</code> and
/// in the <code>func scene(_:, willConnectTo:, options:)</code> method of your <code>UIWindowSceneDelegate</code> if
/// you have one.
/// \param configuration A Setapp configuration to start the framework with.
///
- (void)startWithConfiguration:(STPConfiguration * _Nonnull)configuration;
/// Shows a release notes window if the application is launched for the first time after update.
- (void)showReleaseNotesWindowIfNeeded;
/// Shows a window with release notes.
- (void)showReleaseNotesWindow;
/// Reports special application events that denote app usage.
/// Events must be reported only after the <code>applicationDidFinishLaunching</code> method is called
/// (if applicable).
/// \param usageEvent Setapp event names are described in the knowledge base.
///
- (void)reportUsageEvent:(enum STPUsageEvent)usageEvent;
/// Shows the dialog that offers sharing an email address.
/// Although you should call this method when it makes sense in the user experience flow of your app,
/// the actual display of an email sharing dialog is governed by Setapp policy.
/// For example, the dialog won’t show if user has already shared the email or one was
/// recently shown and user selected “later” option. Each time user selects “later” option,
/// the presentation cooldown increases (up to one month).
- (void)askUserToShareEmail;
@end

/// A protocol that defines the methods that Setapp manager instances call on their delegates to
/// handle events, like subscription changes.
SWIFT_PROTOCOL_NAMED("SetappManagerDelegate")
@protocol STPManagerDelegate
/// Tells the delegate that the Setapp subscription has been updated.
/// \param manager A manager containing a subscription that has been updated.
///
/// \param newSetappSubscription A new Setapp subscription.
///
- (void)setappManager:(STPManager * _Nonnull)manager didUpdateSubscriptionTo:(STPSubscription * _Nonnull)newSetappSubscription;
@end

@class NSDate;
/// An object describing current user’s Setapp subscription state.
SWIFT_CLASS_NAMED("SetappSubscription")
@interface STPSubscription : NSObject
@property (nonatomic, readonly) BOOL isActive;
@property (nonatomic, readonly, copy) NSDate * _Nullable expirationDate;
/// Returns a Boolean value that indicates whether the subscription and a given object are
/// equal.
/// \param object The object to be compared to the receiver. May be nil, in which case
/// this method returns false.
///
///
/// returns:
/// <code>true</code> if the Subscription and <code>object</code> are equal, otherwise <code>false</code>.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// A textual representation of the subscription.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Events used to report how a Setapp member (subscriber) uses Setapp and its apps.
typedef SWIFT_ENUM_NAMED(NSInteger, STPUsageEvent, "SetappUsageEvent", open) {
/// A sign-in event.
  STPUsageEventSignIn = 0,
/// A sign-out event.
  STPUsageEventSignOut = 1,
/// A user interaction event.
  STPUsageEventUserInteraction = 2,
};

/// Describes an <em>exported</em> object capable of handling Setapp XPC service responses (library).
SWIFT_PROTOCOL("_TtP6Setapp17XPCClientProtocol_")
@protocol XPCClientProtocol <NSObject>
@end

/// An <em>exported</em> object capable of handling Setapp XPC service responses.
SWIFT_CLASS("_TtC6Setapp9XPCClient")
@interface XPCClient : NSObject <XPCClientProtocol>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Protocol describing <em>remote</em> object capable of providing API version.
SWIFT_PROTOCOL("_TtP6Setapp22XPCServerAPIVersioning_")
@protocol XPCServerAPIVersioning <NSObject>
/// Fetches the XPC’s API version.
/// \param callback A callback to call when API version is resolved.
/// A callback takes 2 parameters:
/// <code>xpcAPIVersion</code> - A <a href="https://semver.org/spec/v2.0.0.html">semantic version (v2)</a>
/// string of XPC’s API version.
/// <code>error</code> - An error occurred during API version fetch, if any. Can be <code>nil</code>.
///
- (void)xpcAPIVersionWithCallback:(void (^ _Nonnull)(NSString * _Nonnull, NSError * _Nullable))callback;
@end

@class NSNumber;
/// Protocol describing <em>remote</em> object capable of providing purchase type of the app.
SWIFT_PROTOCOL("_TtP6Setapp24XPCServerAppPurchaseType_")
@protocol XPCServerAppPurchaseType <NSObject>
- (void)provideAppPurchaseTypeWithCallback:(void (^ _Nonnull)(NSNumber * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of checking if connection with
/// Setapp XPC service is established.
SWIFT_PROTOCOL("_TtP6Setapp26XPCServerConnectionChecker_")
@protocol XPCServerConnectionChecker <NSObject>
/// Checks if connection with XPC service could be established.
/// warning:
///
/// This will call XPC service (Setapp Agent) and there is a chance that callback will not
/// be executed (if Setapp Agent is not installed or malfunctioning). For that reason you
/// should run additional checks.
/// \param callback A completion handler to call when connection established.
/// The handler will be executed on the main thread. Accepts one parameter:
/// <code>isConnected</code>
/// A <code>Bool</code> with is <code>true</code> if connection is established and can be used,
/// <code>false</code> - otherwise.
///
- (void)checkConnectionWithCallback:(void (^ _Nonnull)(BOOL))callback;
@end

/// Protocol describing <em>remote</em> object capable of providing customer identity.
SWIFT_PROTOCOL("_TtP6Setapp25XPCServerCustomerIdentity_")
@protocol XPCServerCustomerIdentity <NSObject>
- (void)fetchCustomerIdentityWithCallback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of displaying email sharing request.
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerEmailSharing_")
@protocol XPCServerEmailSharing <NSObject>
/// Checks if vendor app <em>can ask</em> customer to share the email with vendor.
/// \param callback A callback to call when it’s determined if vendor app can ask customer
/// to share the email.
/// Takes two parameters:
/// <code>isAskingAllowed</code> - A <code>Bool</code> which is <code>true</code> if vendor app can ask customer to share
/// email, <code>false</code> otherwise.
/// <code>email</code> - An optional <code>String</code> with customer email.
///
- (void)fetchAskingPermissionStatus:(void (^ _Nonnull)(BOOL, NSString * _Nullable))callback;
/// Shows email sharing request window.
/// <ul>
///   <li>
///     Parameters
///     <ul>
///       <li>
///         callback: A callback to call when email sharing request window is closed.
///         Takes two parameters.
///         <code>emailSharingResult</code> - A <code>NSNumber</code> with raw value of <code>SetappEmailSharingResponse</code> enum
///         representing customer’s response.
///         <code>error</code> - An optional <code>NSError</code> object if error occurred.
///       </li>
///     </ul>
///   </li>
/// </ul>
- (void)showEmailSharingRequestForAppWithCallback:(void (^ _Nonnull)(NSNumber * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of providing recovery option URLs for AI errors.
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerRecoveryURLs_")
@protocol XPCServerRecoveryURLs <NSObject>
/// Fetches all available recovery URLs.
/// \param callback A callback to call when recovery URLs are fetched.
/// Takes two parameters:
/// <code>recoveryURLs</code> - An optional <code>NSDictionary</code> with string keys and URL string values.
/// <code>error</code> - An optional <code>NSError</code> object if error occurred.
///
- (void)fetchRecoveryURLs:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of reporting usage events.
SWIFT_PROTOCOL("_TtP6Setapp18XPCServerReporting_")
@protocol XPCServerReporting <NSObject>
/// Reports usage event to the XPC service.
/// \param usageEvent A string representing usage event to report.
///
/// \param eventInfo Additional event info to report.
///
- (void)reportUsageEvent:(NSString * _Nonnull)usageEvent eventInfo:(NSDictionary<NSString *, NSString *> * _Nullable)eventInfo;
@end

/// Protocol describing <em>remote</em> object capable of showing release notes window..
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerReleaseNotes_")
@protocol XPCServerReleaseNotes <NSObject>
/// Determines if a release notes window could be shown (aka if the application is launched for
/// the first time after update).
/// \param callback A callback to call when it’s resolved to show release notes or not.
/// Takes two parameters:
/// <code>shouldShowReleaseNotes</code> - A <code>Bool</code> which is <code>true</code> if it’s the first launch of vendor
/// app after update and release notes should be shown, <code>false</code> otherwise.
/// <code>error</code> - An optional <code>NSError</code> object if error occurred.
///
- (void)shouldShowReleaseNotesForAppWithCallback:(void (^ _Nonnull)(BOOL, NSError * _Nullable))callback;
/// Shows a release notes window if the application is launched for the first time after update.
/// \param callback A callback to call after release notes window is presented.
/// Takes one parameter:
/// \code
/// `error` - An optional `NSError` object if error occurred.
///
/// \endcode
- (void)showReleaseNotesForAppWithCallback:(void (^ _Nonnull)(NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of providing vendor authentication.
SWIFT_PROTOCOL("_TtP6Setapp29XPCServerVendorAuthentication_")
@protocol XPCServerVendorAuthentication <NSObject>
- (void)provideAuthCodeWithClientID:(NSString * _Nonnull)clientID scope:(NSArray<NSString *> * _Nonnull)scope callback:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))callback;
@end

SWIFT_ENUM_FWD_DECL(NSUInteger, STPLicenseVersion)
@class NSData;
@class NSAttributedString;
/// Protocol describing <em>remote</em> object capable of providing raw license data from Setapp XPC service.
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerProvisioning_")
@protocol XPCServerProvisioning <NSObject>
/// ⚠️ Deprecated.
/// Should not be used if newer version is available.
/// Fetches license via API v1-v2.
/// \param licenseVersion A license version to fetch.
///
/// \param appleEvent A current Apple event.
///
/// \param environment Current process environment.
///
/// \param arguments Arguments received on launch.
///
/// \param callback A callback to call when license fetch is complete.
/// Takes <code>four</code>⚠️ parameters:
/// <code>data</code> - license data. Can be <code>nil</code>.
/// <code>shouldPresentReleaseNotes</code> - A <code>Bool</code> indication if release notes should be presented.
/// <code>releaseNotes</code> - An <code>NSAttributedString</code> containing release notes to present. Can be <code>nil</code>.
/// <code>error</code> - An error occurred during license fetch, if any. Can be <code>nil</code>.
///
- (void)fetchLaunchInfoWithLicenseVersion:(enum STPLicenseVersion)licenseVersion appleEvent:(NSObject * _Nullable)appleEvent environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment arguments:(NSArray<NSString *> * _Nonnull)arguments callback:(void (^ _Nonnull)(NSData * _Nullable, BOOL, NSAttributedString * _Nullable, NSError * _Nullable))callback;
/// Fetches licenses for the XPC service.
/// \param licenseVersion A license version to fetch (⚠️ max value should be <code>.version2</code>).
///
/// \param appleEvent A current Apple event.
///
/// \param environment Current process environment.
///
/// \param arguments Arguments received on launch.
///
/// \param callback A callback to call when license fetch is complete.
/// Takes two parameters:
/// <code>data</code> - license data. Can be <code>nil</code>.
/// <code>error</code> - An error occurred during license fetch, if any. Can be <code>nil</code>.
///
- (void)fetchLicenseWithLicenseVersion:(enum STPLicenseVersion)licenseVersion appleEvent:(NSObject * _Nullable)appleEvent environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment arguments:(NSArray<NSString *> * _Nonnull)arguments callback:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))callback;
/// Reports to the XPC server license decoding status.
/// \param version A validated license version .
///
/// \param status License validation status.
///
- (void)didFinishLicenseValidationOfVersion:(enum STPLicenseVersion)version status:(enum LicenseValidationStatus)status;
@end

/// United protocol describing <em>remote</em> object representing Setapp XPC service (Setapp Agent).
SWIFT_PROTOCOL("_TtP6Setapp17XPCServerProtocol_")
@protocol XPCServerProtocol <XPCServerAPIVersioning, XPCServerAppPurchaseType, XPCServerConnectionChecker, XPCServerCustomerIdentity, XPCServerEmailSharing, XPCServerProvisioning, XPCServerRecoveryURLs, XPCServerReleaseNotes, XPCServerReporting, XPCServerVendorAuthentication>
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef SETAPP_SWIFT_H
#define SETAPP_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Setapp",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Setapp",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@interface NSHTTPURLResponse (SWIFT_EXTENSION(Setapp))
/// Backend request identifier.
@property (nonatomic, readonly, copy) NSString * _Nullable requestID;
@end

typedef SWIFT_ENUM(NSInteger, LicenseValidationStatus, closed) {
  LicenseValidationStatusSuccess = 1000,
  LicenseValidationStatusEmptyWorkingDataError = 1010,
  LicenseValidationStatusEmptyServerStatusDataError = 1011,
  LicenseValidationStatusEmptySignatureDataError = 1012,
  LicenseValidationStatusEmptyEncryptedDataError = 1013,
  LicenseValidationStatusDecryptedLicenseDataError = 1014,
  LicenseValidationStatusWorkingDataInvalid = 1020,
  LicenseValidationStatusPublicKeyInvalidError = 1021,
  LicenseValidationStatusSignatureInvalidError = 1022,
  LicenseValidationStatusDecryptionFailedError = 1023,
  LicenseValidationStatusLicenseExpiredError = 1024,
  LicenseValidationStatusUserSysTimeInvalidError = 1025,
  LicenseValidationStatusCrackedError = 1100,
  LicenseValidationStatusBackendReturnedErrorError = 1030,
  LicenseValidationStatusUnknownError = 1999,
};

@interface NSError (SWIFT_EXTENSION(Setapp))
- (nonnull instancetype)initWithCFError:(CFErrorRef _Nonnull)cfError;
@end

@class NSBundle;
/// A configuration object that holds necessary information for the operation of the Setapp
/// framework.
SWIFT_CLASS_NAMED("SetappConfiguration")
@interface STPConfiguration : NSObject
/// The default configuration for the current app.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) STPConfiguration * _Nonnull defaultConfiguration;)
+ (STPConfiguration * _Nonnull)defaultConfiguration SWIFT_WARN_UNUSED_RESULT;
/// An app group identifier used to store usage reports from app extension.
@property (nonatomic, readonly, copy) NSString * _Nullable appGroupIdentifier;
/// A bundle containing a public key file.
@property (nonatomic, readonly, strong) NSBundle * _Nonnull publicKeyBundle;
/// A public key filename.
@property (nonatomic, readonly, copy) NSString * _Nonnull publicKeyFilename;
/// Creates a new configuration with the given parameters.
/// \param publicKeyBundle A bundle containing a public key file. If <code>nil</code>, the main bundle is
/// used.
///
/// \param publicKeyFilename A name of a public key file. If <code>nil</code>, the <code>setappPublicKey.pem</code>
/// string is used.
///
/// \param appGroupIdentifier An app group identifier used to store usage reports from app extension.
///
- (nonnull instancetype)initWithPublicKeyBundle:(NSBundle * _Nullable)publicKeyBundle publicKeyFilename:(NSString * _Nullable)publicKeyFilename appGroupIdentifier:(NSString * _Nullable)appGroupIdentifier OBJC_DESIGNATED_INITIALIZER;
/// Returns a Boolean value that indicates whether the configuration and a given object are
/// equal.
/// \param object The object to be compared to the configuration. May be nil, in which
/// case this method returns false.
///
///
/// returns:
/// <code>true</code> if the configuration and <code>object</code> are equal, otherwise <code>false</code>.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// A textual representation of the configuration.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Setapp log levels.
typedef SWIFT_ENUM_NAMED(NSInteger, STPLogLevel, "SetappLogLevel", open) {
/// Error, warning, information, debug, and verbose logs.
  STPLogLevelVerbose = 0,
/// Error, warning, and information logs.
  STPLogLevelDebug = 1,
/// Error, warning, and information logs.
  STPLogLevelInfo = 2,
/// Error and warning logs.
  STPLogLevelWarning = 3,
/// Error logs only.
  STPLogLevelError = 4,
/// No logs.
  STPLogLevelOff = 5,
};

@protocol STPManagerDelegate;
@class STPSubscription;
@class NSURL;
@class UIOpenURLContext;
/// An object that provides an interface for the Setapp framework.
SWIFT_CLASS_NAMED("SetappManager")
@interface STPManager : NSObject
/// An object that handles Setapp subscription updates.
@property (nonatomic, strong) id <STPManagerDelegate> _Nullable delegate;
/// A current Setapp subscription.
@property (nonatomic, readonly, strong) STPSubscription * _Nullable subscription;
/// Returns <code>true</code> if a URL can be processed by the Setapp iOS Framework; otherwise <code>false</code>.
/// \param url A URL to validate.
///
- (BOOL)canOpenURL:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Returns <code>true</code> if at least one of the URL contexts could be opened by the Setapp iOS Framework,
/// otherwise <code>false</code>.
/// \param urlContexts A set of one or more <code>UIOpenURLContext</code> objects.
///
- (BOOL)canOpenURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)urlContexts SWIFT_WARN_UNUSED_RESULT;
/// A handler to call after handling background URL session events.
@property (nonatomic, copy) void (^ _Nullable backgroundSessionCompletionHandler)(void) SWIFT_DEPRECATED_MSG("This variable is not needed anymore.");
/// Checks if a provided URL session <code>identifier</code> was created by the Setapp framework or not.
/// Returns <code>true</code> if a provided identifier represents background Setapp URL session,
/// otherwise - <code>false</code>.
/// \param identifier The identifier of the URL session to check.
///
+ (BOOL)isSetappBackgroundConfigurationIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT;
/// Checks if a provided URL session <code>identifier</code> was created by the Setapp framework or not.
/// Returns <code>true</code> if a provided identifier represents background Setapp URL session,
/// otherwise - <code>false</code>.
/// \param identifier The identifier of the URL session to check.
///
- (BOOL)isSetappBackgroundSessionIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Instance method is deprecated use the class method instead: \"SetappManager.isSetappBackgroundSessionIdentifier\".");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@interface STPManager (SWIFT_EXTENSION(Setapp))
/// Requests an authorization code for communication with Setapp backend server.
/// The code is used to obtain the access & refresh tokens from the Vendor API.
/// This method requires an active Setapp subscription and an Internet connection,
/// otherwise the request fails with a corresponding error.
/// \param clientID A string ID generated for the app’s client in the Setapp developer account.
///
/// \param scope An array of case-sensitive strings that specify the scope of functionalities
/// to be authorized for the app’s client. See the full list of possible values in the
/// <a href="https://docs.setapp.com/reference#authorization-code-by-setapp-library-grant">Vendor API reference</a>.
///
/// \param completionHandler A completion handler to call once the auth code has been fetched.
/// The handler is executed on the main thread. Accepts one parameter:
/// <code>result</code>
/// A <code>Result</code> with a <code>String</code> as a success value if the code has
/// been fetched successfully. Otherwise, it’s a failure with an error
/// describing why the request failed.
///
- (void)requestAuthorizationCodeWithClientID:(NSString * _Nonnull)clientID scope:(NSArray<NSString *> * _Nonnull)scope completionHandler:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))completionHandler;
@end

@interface STPManager (SWIFT_EXTENSION(Setapp))
/// Attempts to open a Setapp URL.
/// \param url A URL to open.
///
/// \param options A dictionary of URL handling options.
///
/// \param completionHandler A completion handler to call when the Setapp subscription state is
/// resolved.
/// The handler will be executed on the main thread. Accepts two parameters:
/// <code>setappSubscription</code>
/// <code>SetappSubscription</code> if Setapp subscription has been fetched successfully and is valid,
/// or <code>nil</code> if the subscription validation fails.
/// <code>error</code>
/// An error object that specifies why the Setapp subscription validation has failed, or
/// <code>nil</code> if the request was successful.
///
- (BOOL)openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options completionHandler:(void (^ _Nullable)(STPSubscription * _Nullable, NSError * _Nullable))completionHandler SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(maccatalyst,introduced=13.1,deprecated=26.0,message="Use UIScene lifecycle and equivalent properties on UISceneOpenURLOptions from a UIOpenURLContext in UIScene.ConnectionOptions.URLContexts instead.") SWIFT_AVAILABILITY(ios,introduced=9.0,deprecated=26.0,message="Use UIScene lifecycle and equivalent properties on UISceneOpenURLOptions from a UIOpenURLContext in UIScene.ConnectionOptions.URLContexts instead.");
/// Opens Setapp URLs.
/// \param urlContexts A set of one or more <code>UIOpenURLContext</code> objects.
///
/// \param completionHandler A completion handler to call when the Setapp subscription state is
/// resolved.
/// The handler will be executed on the main thread. Accepts two parameters:
/// <code>setappSubscription</code>
/// <code>SetappSubscription</code> if Setapp subscription has been fetched successfully and is valid,
/// or <code>nil</code> if the subscription validation fails.
/// <code>error</code>
/// An error object that specifies why the Setapp subscription validation has failed, or
/// <code>nil</code> if the request was successful.
///
- (void)openURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)urlContexts completionHandler:(void (^ _Nonnull)(STPSubscription * _Nullable, NSError * _Nullable))completionHandler;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, STPUsageEvent)
@interface STPManager (SWIFT_EXTENSION(Setapp))
/// Posted when a current Setapp subscription changes.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull didChangeSubscriptionNotification;)
+ (NSNotificationName _Nonnull)didChangeSubscriptionNotification SWIFT_WARN_UNUSED_RESULT;
/// A shared Setapp manager object for an application.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) STPManager * _Nonnull sharedInstance;)
+ (STPManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Current log level.
/// Default value: <code>SetappLogLevel.info</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) enum STPLogLevel logLevel;)
+ (enum STPLogLevel)logLevel SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogLevel:(enum STPLogLevel)newValue;
/// Sets a log handle for Setapp log messages.
/// \param logHandle A closure to handle log messages. Can be <code>nil</code>. If <code>logHandle</code> is
/// not <code>nil</code>, no messages are printed in the device console.
///
+ (void)setLogHandle:(void (^ _Nullable)(NSString * _Nonnull, enum STPLogLevel))logHandle;
/// Starts the Setapp iOS Framework with a provided configuration.
/// We strongly recommend to call this method as soon as your app opens. You can do this in the
/// <code>application(_:, didFinishLaunchingWithOptions:)</code> method of your <code>UIApplicationDelegate</code> and
/// in the <code>func scene(_:, willConnectTo:, options:)</code> method of your <code>UIWindowSceneDelegate</code> if
/// you have one.
/// \param configuration A Setapp configuration to start the framework with.
///
- (void)startWithConfiguration:(STPConfiguration * _Nonnull)configuration;
/// Shows a release notes window if the application is launched for the first time after update.
- (void)showReleaseNotesWindowIfNeeded;
/// Shows a window with release notes.
- (void)showReleaseNotesWindow;
/// Reports special application events that denote app usage.
/// Events must be reported only after the <code>applicationDidFinishLaunching</code> method is called
/// (if applicable).
/// \param usageEvent Setapp event names are described in the knowledge base.
///
- (void)reportUsageEvent:(enum STPUsageEvent)usageEvent;
/// Shows the dialog that offers sharing an email address.
/// Although you should call this method when it makes sense in the user experience flow of your app,
/// the actual display of an email sharing dialog is governed by Setapp policy.
/// For example, the dialog won’t show if user has already shared the email or one was
/// recently shown and user selected “later” option. Each time user selects “later” option,
/// the presentation cooldown increases (up to one month).
- (void)askUserToShareEmail;
@end

/// A protocol that defines the methods that Setapp manager instances call on their delegates to
/// handle events, like subscription changes.
SWIFT_PROTOCOL_NAMED("SetappManagerDelegate")
@protocol STPManagerDelegate
/// Tells the delegate that the Setapp subscription has been updated.
/// \param manager A manager containing a subscription that has been updated.
///
/// \param newSetappSubscription A new Setapp subscription.
///
- (void)setappManager:(STPManager * _Nonnull)manager didUpdateSubscriptionTo:(STPSubscription * _Nonnull)newSetappSubscription;
@end

@class NSDate;
/// An object describing current user’s Setapp subscription state.
SWIFT_CLASS_NAMED("SetappSubscription")
@interface STPSubscription : NSObject
@property (nonatomic, readonly) BOOL isActive;
@property (nonatomic, readonly, copy) NSDate * _Nullable expirationDate;
/// Returns a Boolean value that indicates whether the subscription and a given object are
/// equal.
/// \param object The object to be compared to the receiver. May be nil, in which case
/// this method returns false.
///
///
/// returns:
/// <code>true</code> if the Subscription and <code>object</code> are equal, otherwise <code>false</code>.
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
/// A textual representation of the subscription.
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Events used to report how a Setapp member (subscriber) uses Setapp and its apps.
typedef SWIFT_ENUM_NAMED(NSInteger, STPUsageEvent, "SetappUsageEvent", open) {
/// A sign-in event.
  STPUsageEventSignIn = 0,
/// A sign-out event.
  STPUsageEventSignOut = 1,
/// A user interaction event.
  STPUsageEventUserInteraction = 2,
};

/// Describes an <em>exported</em> object capable of handling Setapp XPC service responses (library).
SWIFT_PROTOCOL("_TtP6Setapp17XPCClientProtocol_")
@protocol XPCClientProtocol <NSObject>
@end

/// An <em>exported</em> object capable of handling Setapp XPC service responses.
SWIFT_CLASS("_TtC6Setapp9XPCClient")
@interface XPCClient : NSObject <XPCClientProtocol>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Protocol describing <em>remote</em> object capable of providing API version.
SWIFT_PROTOCOL("_TtP6Setapp22XPCServerAPIVersioning_")
@protocol XPCServerAPIVersioning <NSObject>
/// Fetches the XPC’s API version.
/// \param callback A callback to call when API version is resolved.
/// A callback takes 2 parameters:
/// <code>xpcAPIVersion</code> - A <a href="https://semver.org/spec/v2.0.0.html">semantic version (v2)</a>
/// string of XPC’s API version.
/// <code>error</code> - An error occurred during API version fetch, if any. Can be <code>nil</code>.
///
- (void)xpcAPIVersionWithCallback:(void (^ _Nonnull)(NSString * _Nonnull, NSError * _Nullable))callback;
@end

@class NSNumber;
/// Protocol describing <em>remote</em> object capable of providing purchase type of the app.
SWIFT_PROTOCOL("_TtP6Setapp24XPCServerAppPurchaseType_")
@protocol XPCServerAppPurchaseType <NSObject>
- (void)provideAppPurchaseTypeWithCallback:(void (^ _Nonnull)(NSNumber * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of checking if connection with
/// Setapp XPC service is established.
SWIFT_PROTOCOL("_TtP6Setapp26XPCServerConnectionChecker_")
@protocol XPCServerConnectionChecker <NSObject>
/// Checks if connection with XPC service could be established.
/// warning:
///
/// This will call XPC service (Setapp Agent) and there is a chance that callback will not
/// be executed (if Setapp Agent is not installed or malfunctioning). For that reason you
/// should run additional checks.
/// \param callback A completion handler to call when connection established.
/// The handler will be executed on the main thread. Accepts one parameter:
/// <code>isConnected</code>
/// A <code>Bool</code> with is <code>true</code> if connection is established and can be used,
/// <code>false</code> - otherwise.
///
- (void)checkConnectionWithCallback:(void (^ _Nonnull)(BOOL))callback;
@end

/// Protocol describing <em>remote</em> object capable of providing customer identity.
SWIFT_PROTOCOL("_TtP6Setapp25XPCServerCustomerIdentity_")
@protocol XPCServerCustomerIdentity <NSObject>
- (void)fetchCustomerIdentityWithCallback:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of displaying email sharing request.
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerEmailSharing_")
@protocol XPCServerEmailSharing <NSObject>
/// Checks if vendor app <em>can ask</em> customer to share the email with vendor.
/// \param callback A callback to call when it’s determined if vendor app can ask customer
/// to share the email.
/// Takes two parameters:
/// <code>isAskingAllowed</code> - A <code>Bool</code> which is <code>true</code> if vendor app can ask customer to share
/// email, <code>false</code> otherwise.
/// <code>email</code> - An optional <code>String</code> with customer email.
///
- (void)fetchAskingPermissionStatus:(void (^ _Nonnull)(BOOL, NSString * _Nullable))callback;
/// Shows email sharing request window.
/// <ul>
///   <li>
///     Parameters
///     <ul>
///       <li>
///         callback: A callback to call when email sharing request window is closed.
///         Takes two parameters.
///         <code>emailSharingResult</code> - A <code>NSNumber</code> with raw value of <code>SetappEmailSharingResponse</code> enum
///         representing customer’s response.
///         <code>error</code> - An optional <code>NSError</code> object if error occurred.
///       </li>
///     </ul>
///   </li>
/// </ul>
- (void)showEmailSharingRequestForAppWithCallback:(void (^ _Nonnull)(NSNumber * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of providing recovery option URLs for AI errors.
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerRecoveryURLs_")
@protocol XPCServerRecoveryURLs <NSObject>
/// Fetches all available recovery URLs.
/// \param callback A callback to call when recovery URLs are fetched.
/// Takes two parameters:
/// <code>recoveryURLs</code> - An optional <code>NSDictionary</code> with string keys and URL string values.
/// <code>error</code> - An optional <code>NSError</code> object if error occurred.
///
- (void)fetchRecoveryURLs:(void (^ _Nonnull)(NSDictionary * _Nullable, NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of reporting usage events.
SWIFT_PROTOCOL("_TtP6Setapp18XPCServerReporting_")
@protocol XPCServerReporting <NSObject>
/// Reports usage event to the XPC service.
/// \param usageEvent A string representing usage event to report.
///
/// \param eventInfo Additional event info to report.
///
- (void)reportUsageEvent:(NSString * _Nonnull)usageEvent eventInfo:(NSDictionary<NSString *, NSString *> * _Nullable)eventInfo;
@end

/// Protocol describing <em>remote</em> object capable of showing release notes window..
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerReleaseNotes_")
@protocol XPCServerReleaseNotes <NSObject>
/// Determines if a release notes window could be shown (aka if the application is launched for
/// the first time after update).
/// \param callback A callback to call when it’s resolved to show release notes or not.
/// Takes two parameters:
/// <code>shouldShowReleaseNotes</code> - A <code>Bool</code> which is <code>true</code> if it’s the first launch of vendor
/// app after update and release notes should be shown, <code>false</code> otherwise.
/// <code>error</code> - An optional <code>NSError</code> object if error occurred.
///
- (void)shouldShowReleaseNotesForAppWithCallback:(void (^ _Nonnull)(BOOL, NSError * _Nullable))callback;
/// Shows a release notes window if the application is launched for the first time after update.
/// \param callback A callback to call after release notes window is presented.
/// Takes one parameter:
/// \code
/// `error` - An optional `NSError` object if error occurred.
///
/// \endcode
- (void)showReleaseNotesForAppWithCallback:(void (^ _Nonnull)(NSError * _Nullable))callback;
@end

/// Protocol describing <em>remote</em> object capable of providing vendor authentication.
SWIFT_PROTOCOL("_TtP6Setapp29XPCServerVendorAuthentication_")
@protocol XPCServerVendorAuthentication <NSObject>
- (void)provideAuthCodeWithClientID:(NSString * _Nonnull)clientID scope:(NSArray<NSString *> * _Nonnull)scope callback:(void (^ _Nonnull)(NSString * _Nullable, NSError * _Nullable))callback;
@end

SWIFT_ENUM_FWD_DECL(NSUInteger, STPLicenseVersion)
@class NSData;
@class NSAttributedString;
/// Protocol describing <em>remote</em> object capable of providing raw license data from Setapp XPC service.
SWIFT_PROTOCOL("_TtP6Setapp21XPCServerProvisioning_")
@protocol XPCServerProvisioning <NSObject>
/// ⚠️ Deprecated.
/// Should not be used if newer version is available.
/// Fetches license via API v1-v2.
/// \param licenseVersion A license version to fetch.
///
/// \param appleEvent A current Apple event.
///
/// \param environment Current process environment.
///
/// \param arguments Arguments received on launch.
///
/// \param callback A callback to call when license fetch is complete.
/// Takes <code>four</code>⚠️ parameters:
/// <code>data</code> - license data. Can be <code>nil</code>.
/// <code>shouldPresentReleaseNotes</code> - A <code>Bool</code> indication if release notes should be presented.
/// <code>releaseNotes</code> - An <code>NSAttributedString</code> containing release notes to present. Can be <code>nil</code>.
/// <code>error</code> - An error occurred during license fetch, if any. Can be <code>nil</code>.
///
- (void)fetchLaunchInfoWithLicenseVersion:(enum STPLicenseVersion)licenseVersion appleEvent:(NSObject * _Nullable)appleEvent environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment arguments:(NSArray<NSString *> * _Nonnull)arguments callback:(void (^ _Nonnull)(NSData * _Nullable, BOOL, NSAttributedString * _Nullable, NSError * _Nullable))callback;
/// Fetches licenses for the XPC service.
/// \param licenseVersion A license version to fetch (⚠️ max value should be <code>.version2</code>).
///
/// \param appleEvent A current Apple event.
///
/// \param environment Current process environment.
///
/// \param arguments Arguments received on launch.
///
/// \param callback A callback to call when license fetch is complete.
/// Takes two parameters:
/// <code>data</code> - license data. Can be <code>nil</code>.
/// <code>error</code> - An error occurred during license fetch, if any. Can be <code>nil</code>.
///
- (void)fetchLicenseWithLicenseVersion:(enum STPLicenseVersion)licenseVersion appleEvent:(NSObject * _Nullable)appleEvent environment:(NSDictionary<NSString *, NSString *> * _Nonnull)environment arguments:(NSArray<NSString *> * _Nonnull)arguments callback:(void (^ _Nonnull)(NSData * _Nullable, NSError * _Nullable))callback;
/// Reports to the XPC server license decoding status.
/// \param version A validated license version .
///
/// \param status License validation status.
///
- (void)didFinishLicenseValidationOfVersion:(enum STPLicenseVersion)version status:(enum LicenseValidationStatus)status;
@end

/// United protocol describing <em>remote</em> object representing Setapp XPC service (Setapp Agent).
SWIFT_PROTOCOL("_TtP6Setapp17XPCServerProtocol_")
@protocol XPCServerProtocol <XPCServerAPIVersioning, XPCServerAppPurchaseType, XPCServerConnectionChecker, XPCServerCustomerIdentity, XPCServerEmailSharing, XPCServerProvisioning, XPCServerRecoveryURLs, XPCServerReleaseNotes, XPCServerReporting, XPCServerVendorAuthentication>
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
